### ISSUE TITLE
Error: Protocol error (Target.closeTarget): Target closed.

### ISSUE THREAD

**Issue by yeekit-jewel** [yujiosaka/headless-chrome-crawler#344]
**What is the current behavior?**
`(node:61647) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.closeTarget): Target closed.
    at Promise (/Users/yeekitng/Documents/GitHub/OS-ScraperV1/node_modules/puppeteer/lib/Connection.js:86:56)
    at new Promise (<anonymous>)
    at Connection.send (/Users/yeekitng/Documents/GitHub/OS-ScraperV1/node_modules/puppeteer/lib/Connection.js:85:12)
    at Page.close (/Users/yeekitng/Documents/GitHub/OS-ScraperV1/node_modules/puppeteer/lib/Page.js:888:38)
    at Crawler.close (/Users/yeekitng/Documents/GitHub/OS-ScraperV1/node_modules/headless-chrome-crawler/lib/crawler.js:80:22)
    at Crawler.<anonymous> (/Users/yeekitng/Documents/GitHub/OS-ScraperV1/node_modules/headless-chrome-crawler/lib/helper.js:177:23)
    at HCCrawler._request (/Users/yeekitng/Documents/GitHub/OS-ScraperV1/node_modules/headless-chrome-crawler/lib/hccrawler.js:349:21)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)`

**If the current behavior is a bug, please provide the steps to reproduce**
just run the code and you will run into this error randomly

**Please tell us about your environment:**

- Version: 1.8.0
- Platform / OS version: macOS High Sierra version 10.13.6
- Node.js version: 11.6.0

**Comment by yeekit-jewel** [comment]
i solved this by temporary comment out the `line 349` in `node_modules/headless-chrome-crawler/lib/hccrawler.js`:

> //await crawler.close();

I think it is due to the code somehow run into the exception after you close the crawler in your try block.

**Comment by mike-aungsan** [comment]
@yeekit-jewel  Thanks. Finally, I am able to see what is the real error.

**Comment by popstas** [comment]
Error appears after `maxrequestreached` fired. My proposal:

``` js
      try {
        await crawler.close();
      } catch(e){
        // suppress if maxrequestreached happened
      }
```
