### ISSUE TITLE
WebSocket is not open

### ISSUE THREAD

**Issue by mike-aungsan** [yujiosaka/headless-chrome-crawler#348]
- Version: headless-chrome-crawler@1.8.0
- Platform / OS version: 
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

- Node.js version:
v11.10.0

- link: https://www.forever21.com/us/shop/catalog/product/f21/promo-50-70-off-select-single-styles-women/2000307044

(node:16789) UnhandledPromiseRejectionWarning: Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/home/abc/agent/node_modules/ws/lib/websocket.js:314:19)
    at Connection.send (/home/abc/agent/node_modules/headless-chrome-crawler/node_modules/puppeteer/lib/Connection.js:84:21)
    at Browser._createPageInContext (/home/abc/agent/node_modules/headless-chrome-crawler/node_modules/puppeteer/lib/Browser.js:168:47)
    at BrowserContext.newPage (/home/abc/agent/node_modules/headless-chrome-crawler/node_modules/puppeteer/lib/Browser.js:260:26)
    at Browser.newPage (/home/abc/agent/node_modules/headless-chrome-crawler/node_modules/puppeteer/lib/Browser.js:160:33)
    at HCCrawler._newCrawler (/home/abc/agent/node_modules/headless-chrome-crawler/lib/hccrawler.js:554:38)
    at HCCrawler._request (/home/abc/agent/node_modules/headless-chrome-crawler/lib/hccrawler.js:336:32)
    at HCCrawler._request (/home/abc/agent/node_modules/headless-chrome-crawler/lib/hccrawler.js:358:19)
(node:16789) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:16789) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by haroonabbasi** [comment]
Hey, any update on this, i am facing the same issue?

**Comment by matheuschimelli** [comment]
Can you post an snnipt from your code?

**Comment by haroonabbasi** [comment]
sure,

**Comment by haroonabbasi** [comment]
i was testing sample code mentioned here.

**Comment by haroonabbasi** [comment]
Hey i was testing the sample code mentioned here
https://github.com/yujiosaka/headless-chrome-crawler#usage

its my bad i guess, sorry. i commented the line `await crawler.onIdle()` 
which caused the error when I enabled it again. the code worked.

thanks for the quick response!

**Comment by matheuschimelli** [comment]
Nice. I suggest you to post the code here to make it available to others that have the same trouble.

**Comment by haroonabbasi** [comment]
the simple example code worked for me 

```
const HCCrawler = require('headless-chrome-crawler');

(async () => {
  const crawler = await HCCrawler.launch({
    // Function to be evaluated in browsers
    evaluatePage: (() => ({
      title: $('title').text(),
    })),
    // Function to be called with evaluated results from browsers
    onSuccess: (result => {
      console.log(result);
    }),
  });
  // Queue a request
  await crawler.queue('https://www.google.com');

  await crawler.onIdle(); // Resolved when no queue is left
  await crawler.close(); // Close the crawler
})();
```

`await crawler.onIdle();` not having this link generated similar error as mentioned above.

**Comment by kulikalov** [comment]
Hey @mike-aungsan the issue is caused by imperfect error handling. In my case, it was an error happening in the `onSuccess` handler.
