### ISSUE TITLE
how disabled "UnhandledPromiseRejectionWarning: Error: Protocol error"

### ISSUE THREAD

**Issue by hktalent** [yujiosaka/headless-chrome-crawler#367]
```
(node:34367) UnhandledPromiseRejectionWarning: Error: Protocol error (Network.getCookies): Target closed.
    at /node_modules/puppeteer/lib/Connection.js:202:56
    at new Promise (<anonymous>)
    at CDPSession.send (/node_modules/puppeteer/lib/Connection.js:201:12)
    at Page.cookies (/node_modules/puppeteer/lib/Page.js:320:32)
    at Crawler._getCookies (/node_modules/headless-chrome-crawler/lib/crawler.js:271:23)
    at Crawler.crawl (/node_modules/headless-chrome-crawler/lib/crawler.js:60:12)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async HCCrawler.customCrawl [as _customCrawl] (/myCrawler/testCrawler.js:34:22)
    at async HCCrawler._request (/node_modules/headless-chrome-crawler/lib/hccrawler.js:338:19)
    at async HCCrawler._startRequest (/node_modules/headless-chrome-crawler/lib/hccrawler.js:305:19)
    at async Promise.all (index 0)
    at async PriorityQueue._pull (/node_modules/headless-chrome-crawler/lib/priority-queue.js:94:5)
(node:34367) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 56)
```

**Comment by hktalent** [comment]
like
https://github.com/yujiosaka/headless-chrome-crawler/issues/344
