### ISSUE TITLE
Protocol error: Connection closed. Most likely the page has been closed.

### ISSUE THREAD

**Issue by redhotchili** [yujiosaka/headless-chrome-crawler#375]
Hi, so I'm running the crawler on AWS lambda and am finding an issue on some websites, was hoping you might have any insights. 

So the issue is that the crawler crashes after crawling anywhere between ~20-120 pages with the following error:

```
{
  "errorType": "Runtime.UnhandledPromiseRejection",
  "errorMessage": "Error: Protocol error: Connection closed. Most likely the page has been closed.",
  "trace": [
    "Runtime.UnhandledPromiseRejection: Error: Protocol error: Connection closed. Most likely the page has been closed.",
    "    at process.<anonymous> (/var/runtime/index.js:35:15)",
    "    at process.emit (events.js:314:20)",
    "    at processPromiseRejections (internal/process/promises.js:209:33)",
    "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
  ]
}
```

Each time it's a different number of URLs that it manages to complete (even when rerunning for the same website). The lambda timeout is not reached (each time it's around 20-50s before the crash). There is 3008Mb allocated for the lambda, but the crawler uses under 2000Mb, never reaching the limit. 

Is there perhaps a config or a flag that I'm missing here? 

The code:
```
const HCCrawler = require('headless-chrome-crawler');
const chromium = require('chrome-aws-lambda');
var URL = require('url').URL;

const crawl = async (url) => {
  const visitedURLs = []
  const { host } = new URL(url)

  const crawler = await HCCrawler.launch({
    executablePath: await chromium.executablePath,
    defaultViewport: chromium.defaultViewport,
    ignoreHTTPSErrors: true,
    headless: chromium.headless,
    args: chromium.args,
    // Function to be evaluated in headless Chromium
    evaluatePage: () => ({
      title: $('title').text(), // eslint-disable-line no-undef
      link: $('a').attr('href'), // eslint-disable-line no-undef
      linkslen: $('a').length, // eslint-disable-line no-undef
    }),
    onSuccess: async (result) => {
      visitedURLs.push(result.options.url)
      console.log(visitedURLs.length, result.options.url)
      for (const link of result.links) {
        await crawler.queue({ url: link, maxDepth: 1 })
      }
    },
    onError: async (error) => {
      console.log('Failed: ' + error.options.url)
    },
    maxDepth: 1,
    allowedDomains: [host],
    //dumpio: true
  })

  // Queue a request
  await crawler.queue({
    url: url
  })
  await crawler.onIdle() // Resolved when no queue is left
  await crawler.close() // Close the crawler// De-dupe the crawled paths

  return [...new Set(visitedURLs)]
}

exports.handler = async () => {

  const uniqueURLs = await crawl(
    process.env.HTTP_URL
  )
    console.log(uniqeURLs)
}

```

**If the current behavior is a bug, please provide the steps to reproduce**
Run the above code against https://www.bbc.co.uk/

**What is the expected behavior?**
Would expect to crawl all the URLs or timeout when function timeout is reached.
For example on www.chromium.org it crawls through over 600 URLs before lambda timing out at 5mins as expected.

**What is the motivation / use case for changing the behavior?**
To get the crawler working on all websites.

**Please tell us about your environment:**

- Versions:
    "headless-chrome-crawler": "^1.8.0",
    "chrome-aws-lambda": "^5.3.1",
    "puppeteer-core": "^5.3.0",
- Platform / OS version: Linux (AWS Lambda)
- Node.js version: nodejs12.x

**Comment by redhotchili** [comment]
In case anyone else has the same issue - it got solved by setting max concurrency to 1.
